name: test image

on:
  workflow_dispatch:

  workflow_run:
    workflows: [ Build ]
    types:
      - completed

jobs:
  test-image:
    runs-on: ubuntu-latest
    container:
      12build/tsa:latest
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)